[package]
name = "bf-jit"
version = "0.1.0"
authors = ["mrowqa <artur.jamro@gmail.com>", "Andrii Dmytrenko <refresh.xss@gmail.com>"]
edition = "2024"

[dependencies]
libc = "0.2"
thiserror = "2.0.17"
